### ISSUE TITLE
Symbol not found: _CCtsp_solve_dat

### ISSUE THREAD

**Issue by michelgokan** [jvkersch/pyconcorde#22]
I'm using Python 3.8.1 on Mac OS X. I've succefully installed pyconcorde without any errors but when I want to import TSPSolver using `from concorde.tsp import TSPSolver` I'm getting the "Symbol not found: _CCtsp_solve_dat" error. It seems `concorde/tsp.py` cannot import _CCtsp_solve_dat from concorde._concorde in line 10:

```
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    main(args)
  File "main.py", line 10, in main
    experiment = importlib.import_module(f"alphatsp.experiments.{args.experiment}")
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/michelgokan/Documents/Temp2/AlphaTSP/alphatsp/experiments/selfplay.py", line 3, in <module>
    import alphatsp.solvers.exact
  File "/Users/michelgokan/Documents/Temp2/AlphaTSP/alphatsp/solvers/exact.py", line 1, in <module>
    from concorde.tsp import TSPSolver
  File "/Users/michelgokan/pyconcorde/concorde/tsp.py", line 10, in <module>
    from concorde._concorde import _CCutil_gettsplib, _CCtsp_solve_dat
ImportError: dlopen(/Users/michelgokan/pyconcorde/concorde/_concorde.cpython-38-darwin.so, 2): Symbol not found: _CCtsp_solve_dat
  Referenced from: /Users/michelgokan/pyconcorde/concorde/_concorde.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/michelgokan/pyconcorde/concorde/_concorde.cpython-38-darwin.so
```

**Comment by michelgokan** [comment]
New update: Downgrading to 3.7.6 didn't fix the issue

**Comment by michelgokan** [comment]
Update 2: Using Python 2.7 didn't fix the issue either.

```
Python 2.7.17 (default, Dec 23 2019, 21:25:33) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from concorde.tsp import TSPSolver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "concorde/tsp.py", line 10, in <module>
    from concorde._concorde import _CCutil_gettsplib, _CCtsp_solve_dat
ImportError: dlopen(concorde/_concorde.so, 2): Symbol not found: _CCtsp_solve_dat
  Referenced from: concorde/_concorde.so
  Expected in: flat namespace
 in concorde/_concorde.so
```

**Comment by michelgokan** [comment]
Update 3: I've tried the exact same procedure on a fresh Ubuntu 18.04 installation and everything works pretty well! It might be the case that there are some inconsistencies in my Mac's libraries, I'm not sure. Any guides on how to debug and fix the problem?

**Comment by jvkersch** [comment]
@michelgokan Thanks for reporting the problem and for doing the investigation. I currently don't have access to a Mac to test, but this is worrisome since Mac OS is supposed to be a supported platform. I'll try to reproduce in the next few days.

**Comment by iliailmer** [comment]
Hi, have the same issue but running on an M1 macbook pro with arm64 architecture, seems like it requires a different concorde build?

**Comment by jvkersch** [comment]
@iliailmer Thanks for the follow-up. I am not sure about how to support the M1. One thing to note is that I am planning to move to a new API that runs Concorde in a subprocess (see https://github.com/jvkersch/pyconcorde/issues/28#issuecomment-770354999). If you can get Concorde to compile and run on your platform, then this new API should be compatible with it. I'd be very interested in hearing your experiences.

**Comment by iliailmer** [comment]
@jvkersch Hey, thanks for the response. I will check it out and let you know.

**Comment by iliailmer** [comment]
@jvkersch Hey does this require downloading QS_opt or CPLEX as well?

**Comment by samvanderpoel** [comment]
Hi I am having this same problem on MacOS 12.2.1. I got the following warnings before building
`WARNING: Missing build requirements in pyproject.toml for file:///Users/samvanderpoel/Desktop/Projects/TSP/test_dir/pyconcorde.`
`WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.`
even though I had setuptools, numpy, and cython installed. Then
`ImportError: dlopen(/Users/samvanderpoel/Desktop/Projects/TSP/test_dir/pyconcorde/concorde/_concorde.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_QSadd_cols'`
when trying to import.

It is strange because I have previously been able to install and use pyconcorde successfully on the same machine.

Any updates on how to solve this problem?

**Comment by DangerousDyl** [comment]
Hi I am receiving the same issue:
```
dlopen(/Users/dylanjohnson/gnn-tsp/pyconcorde/concorde/_concorde.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_QSadd_cols'
```
Thanks,
Dylan

**Comment by Technophobe01** [comment]
I was able to resolve this problem. This error appears to be caused by an incompatibility between compiling and linking libraries compiled with clang and GCC, that the fact that the underlying Concorde library has no config for MacOSX.

1. Before running `pip install -e .` you need to go into the `./pyconcorde/build/concorde` directory and manually configure it to build and compile concorde.

## Reproduction of Error:
```
git clone https://github.com/jvkersch/pyconcorde.git
cd pyconcorde
pip install -e .                                                                                 [2.7.2]
Obtaining file:///Users/.../test/pyconcorde
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: cython>=0.22.0 in /Users/.../venv/lib/python3.9/site-packages (from pyconcorde==0.1.0) (0.29.33)
Requirement already satisfied: numpy>=1.10.0 in /Users/.../venv/lib/python3.9/site-packages (from pyconcorde==0.1.0) (1.24.2)
Building wheels for collected packages: pyconcorde
  Building editable for pyconcorde (pyproject.toml) ... done
  Created wheel for pyconcorde: filename=pyconcorde-0.1.0-0.editable-cp39-cp39-macosx_13_0_x86_64.whl size=3596 sha256=ea7722c0faad213b7eef0d80b7d7fb0582dd2ff94aa99c7b022658eb35a99dce
  Stored in directory: /private/var/folders/0m/scybmx2x643b9hw9_yjtrky00000gn/T/pip-ephem-wheel-cache-twt6ev3o/wheels/01/52/9c/470b44bc70ceef5ac677fc113e6af8de1a54bd719607b55284
Successfully built pyconcorde
Installing collected packages: pyconcorde
  Attempting uninstall: pyconcorde
    Found existing installation: pyconcorde 0.1.0
    Uninstalling pyconcorde-0.1.0:
      Successfully uninstalled pyconcorde-0.1.0
Successfully installed pyconcorde-0.1.0
(venv).../test/pyconcorde (master●)$ python3                                                                                         [2.7.2]
Python 3.9.16 (main, Dec  7 2022, 10:16:11)
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from concorde.tsp import TSPSolver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/.../test/pyconcorde/concorde/tsp.py", line 10, in <module>
    from concorde._concorde import _CCutil_gettsplib, _CCtsp_solve_dat
ImportError: dlopen(/Users/.../test/pyconcorde/concorde/_concorde.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_QSadd_cols'
>>>
```

## Resolution of Error:
```
unalias gcc
cd build/concorde
mkdir QSOPT;cd QSOPT
wget 'https://www.math.uwaterloo.ca/~bico/qsopt/downloads/codes/mac64/qsopt.gz'
wget 'https://www.math.uwaterloo.ca/~bico/qsopt/downloads/codes/mac64/qsopt.a.gz'
wget 'https://www.math.uwaterloo.ca/~bico/qsopt/downloads/codes/mac64/qsopt.h'
gunzip qsopt.a.gz
cd ..
export QSOPTDIR=`pwd`/QSOPT
export CFLAGS="-g -O3 -arch x86_64"
./configure --with-qsopt=$QSOPTDIR --host=darwin
make

# Check build succeeded
ls -la TSP/concorde

# go back to pyconcorde directory
cd ../../
export QSOPT_DIR=`pwd`/build/concorde/QSOPT
export CONCORDE_DIR=`pwd`/build/concorde/
pip install -e . 
Obtaining file:///Users/pkjar/Cloud/Dropbox/dev/stackoverflow/75792660/test/pyconcorde
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cython>=0.22.0 in /usr/local/lib/python3.11/site-packages (from pyconcorde==0.1.0) (0.29.33)
Requirement already satisfied: numpy>=1.10.0 in /usr/local/lib/python3.11/site-packages (from pyconcorde==0.1.0) (1.24.2)
Installing collected packages: pyconcorde
  Running setup.py develop for pyconcorde
Successfully installed pyconcorde-0.1.0

python3
Python 3.11.2 (main, Mar 24 2023, 00:31:37) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from concorde.tsp import TSPSolver
>>>

```

**Comment by Entman** [comment]
Just wanted to chime an and confirm that the above solution works, one note - if the "unalias gcc" command isn't working for you chances are you just simply don't have gcc installed like I did - in this case you just simply need to install it with Homebrew. 
@Technophobe01 thanks for the fix. I am toying with an idea of making a youtube video that would show how to install this library on mac, given the fact that I've spent a good few hours fighting with this shit lel

**Comment by rgan19** [comment]
I was stuck trying to install this for a couple of hours on my Mac and came across this. Also had this error: `symbol not found in flat namespace '_QSadd_cols'`.  Had to install gcc with homebrew (`brew install gcc`), find the path then `export CC="/usr/local/Cellar/gcc/13.1.0/bin/gcc-13"`. This line is really important. 

@Technophobe01 Thanks for the fix, saved the day.

It finally worked.

**Comment by jvkersch** [comment]
This is very strange; the build process should normally pull in QSOpt and link against it correctly. I have no idea why this happens and I cannot reproduce it on my machine either. It would be very helpful if someone who encountered this problem in the past could find the Concorde shared library (compiled with the instructions in the README, not with the workaround) in the `pyconcorde/concorde` directory and run `otool` and `nm` on it. For example, I get the following:
```
$ otool -L _concorde.cpython-310-darwin.so                         (pyconcorde)
_concorde.cpython-310-darwin.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```
and
```
$ nm -g _concorde.cpython-310-darwin.so | grep _QSadd_cols         (pyconcorde)
0000000000053974 T _QSadd_cols
```

Also, anything else that you could find to pinpoint the problem would be helpful. I am in the process of moving the library to a subprocess-based approach, which will make this issue go away in due course, but I would like to resolve this issue right now to avoid having people lose more time on it.

**Comment by jiajinghu19** [comment]
@Technophobe01 I am trying your solution, but with the line of 

`./configure --with-qsopt=$QSOPTDIR --host=darwin` 

it gave an error 

`loading cache ./config.cache
checking host system type... Invalid configuration `darwin': machine `darwin' not recognized

checking for prespecified compiler options... no
checking for gcc... /usr/local/Cellar/gcc/13.1.0/bin/gcc-13
checking whether the C compiler (/usr/local/Cellar/gcc/13.1.0/bin/gcc-13 -g -O3 -arch x86_64 ) works... no
configure: error: installation or configuration problem: C compiler cannot create executables.`

**Comment by eric-gitta-moore** [comment]
same here.

and it same intro another problem.

```
❯ python examples/us_state_capitals.py
Traceback (most recent call last):
  File "examples/us_state_capitals.py", line 7, in <module>
    from concorde.tsp import TSPSolver
  File "/home/linux/workspace/pyconcorde/concorde/tsp.py", line 10, in <module>
    from concorde._concorde import _CCutil_gettsplib, _CCtsp_solve_dat
ImportError: /home/linux/workspace/pyconcorde/concorde/_concorde.cpython-38-x86_64-linux-gnu.so: undefined symbol: CCutil_dheap_free
```

**Comment by eric-gitta-moore** [comment]
update2: I can directly run the program according to the README in macOS 15 without making any modifications.

**Comment by Antoniano1963** [comment]
> 同样在这里。
> 
> 这同样也引发了另一个问题。
> 
> ```
> ❯ cat /etc/os-release                                                  
> PRETTY_NAME="Ubuntu 24.04.2 LTS"
> NAME="Ubuntu"
> VERSION_ID="24.04"
> VERSION="24.04.2 LTS (Noble Numbat)"
> VERSION_CODENAME=noble
> ID=ubuntu
> ID_LIKE=debian
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> UBUNTU_CODENAME=noble
> LOGO=ubuntu-logo
> ❯ uname -a
> Linux DESKTOP-SURJD4A 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
> ❯ python examples/us_state_capitals.py
> Traceback (most recent call last):
>   File "examples/us_state_capitals.py", line 7, in <module>
>     from concorde.tsp import TSPSolver
>   File "/home/linux/workspace/pyconcorde/concorde/tsp.py", line 10, in <module>
>     from concorde._concorde import _CCutil_gettsplib, _CCtsp_solve_dat
> ImportError: /home/linux/workspace/pyconcorde/concorde/_concorde.cpython-38-x86_64-linux-gnu.so: undefined symbol: CCutil_dheap_free
> ❯ nm -g _concorde.cpython-38-x86_64-linux-gnu.so | grep dheap_free
>                  U CCutil_dheap_free
> ```
have the same problem, how to fix this?
