### ISSUE TITLE
support system

### ISSUE THREAD

**Issue by no-wings** [jvkersch/pyconcorde#24]
when i install it on ubount, it failed. the erro is like that:
 
checking host system type... configure: error: can not guess host type; you must specify one
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/graph-convnet-tsp/data/pyconcorde/setup.py", line 174, in <module>
        'build_ext': build_ext,
      File "/home/xiong/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/xiong/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/xiong/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/xiong/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/xiong/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/xiong/anaconda3/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/xiong/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/xiong/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/graph-convnet-tsp/data/pyconcorde/setup.py", line 115, in run
        build_concorde()
      File "/home/graph-convnet-tsp/data/pyconcorde/setup.py", line 99, in build_concorde
        _run(cwd, "build/concorde")
      File "/home/graph-convnet-tsp/data/pyconcorde/setup.py", line 76, in _run
        subprocess.check_call(cmd, shell=True, cwd=cwd)
      File "/home/xiong/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'CFLAGS="-fPIC -O2 -g" ./configure --prefix /home/graph-convnet-tsp/data/pyconcorde/data --with-qsopt=/home/graph-convnet-tsp/data/pyconcorde/data ' returned non-zero exit status 1.
    building concorde
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/xiong/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/graph-convnet-tsp/data/pyconcorde/setup.py'"'"'; __file__='"'"'/home/graph-convnet-tsp/data/pyconcorde/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by tao0708** [comment]
I also have a issue when i run"pip install -e .", the error is as follows.

KeyError: 'Windows'
    qsopt is missing, downloading

    ----------------------------------------
Command "C:\Users\mac\Anaconda3\python.exe -c "import setuptools, tokenize;__file__='C:\\cygwin64\\home\\pyconcorde\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\cygwin64\home\pyconcorde\

---------------------------

How to fix it?

**Comment by jvkersch** [comment]
Thanks @jackpickford1643 for the assistance! 

I will close this issue for now, but please let me know if the problem persists.
