### ISSUE TITLE
Error when I try to install pyconcorde no Windows

### ISSUE THREAD

**Issue by avelin0** [jvkersch/pyconcorde#61]
Hello, 

It gives me the next error when trying to install on Windows. In Linux, It works whell. Any plano to solve this issue?

Thankx in advance.

Using cached Cython-3.0.0-cp39-cp39-win_amd64.whl (2.8 MB)
Building wheels for collected packages: pyconcorde
  Building editable for pyconcorde (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for pyconcorde (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [110 lines of output]
      running editable_wheel
      creating C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde.egg-info
      writing C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde.egg-info\PKG-INFO
      writing dependency_links to C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde.egg-info\dependency_links.txt
      writing requirements to C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde.egg-info\requires.txt
      writing top-level names to C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde.egg-info\top_level.txt
      writing manifest file 'C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde.egg-info\SOURCES.txt'
      reading manifest file 'C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'COPYING'
      writing manifest file 'C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde.egg-info\SOURCES.txt'
      creating 'C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde-0.1.0.dist-info'
      C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\normal\Lib\site-packages\wheel\bdist_wheel.py:100: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
        if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
      creating C:\Users\bruno\AppData\Local\Temp\pip-wheel-_4983t8b\.tmp-i4xqn6k4\pyconcorde-0.1.0.dist-info\WHEEL
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 344, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 267, in _run_build_commands
          self._run_build_subcommands()
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 294, in _run_build_subcommands
          self.run_command(name)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 119, in run
        File "<string>", line 76, in download_concorde_qsopt
      KeyError: 'Windows'
      C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\_distutils\dist.py:988: _DebuggingTips: Problem in editable installation.
      !!

              ********************************************************************************
              An error happened while installing `pyconcorde` in editable mode.

              The following steps are recommended to help debug this problem:

              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.

              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:

                  https://github.com/pypa/setuptools/issues

              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************

      !!
        cmd_obj.run()
      qsopt is missing, downloading
      Traceback (most recent call last):
        File "C:\Users\bruno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\bruno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\bruno\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\build_meta.py", line 445, in build_editable
          return self._build_with_temp_dir(
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 146, in <module>
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 344, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 267, in _run_build_commands
          self._run_build_subcommands()
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 294, in _run_build_subcommands
          self.run_command(name)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\bruno\AppData\Local\Temp\pip-build-env-erltztqz\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 119, in run
        File "<string>", line 76, in download_concorde_qsopt
      KeyError: 'Windows'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for pyconcorde
Failed to build pyconcorde
ERROR: Could not build wheels for pyconcorde, which is required to install pyproject.toml-based projects

**Comment by turambar928** [comment]
im having the same problem, have you solved it now?

**Comment by avelin0** [comment]
No, unfortunately
